name: "Lint"

on: [push, workflow_dispatch]

jobs:
  call-workflow:
    uses: michijs/.github/.github/workflows/lint.yml@main
    name: "Run lint"
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}