name: "Lint"

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: michijs/.github/.github/workflows/lint.yml@main
    name: "Run lint"
    secrets: inherit
